import type { Metadata } from 'next';
import { Sohne, Bagoss } from '@/assets/fonts/localfont';
import '@/assets/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${Bagoss.variable} ${Sohne.variable} antialiased`}>{children}</body>
    </html>
  );
}
